sudo: required
dist: trusty
language: node_js

node_js:
- '7'

php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'

addons:
  ssh_known_hosts: 139.59.62.25

install:
- npm install
- composer install

script:
- npm test
- composer test

before_deploy:
- openssl aes-256-cbc -K $encrypted_837b9fca4048_key -iv $encrypted_837b9fca4048_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
