sudo: required
dist: trusty
language: node_js

node_js:
  - '6'
  - '7'

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - 'npm install'
  - 'composer install'

script:
  - 'npm test'
  - 'composer test'
